# Project
version=1.0.0
group=tfc.smallerunits
license=MIT
credits=

# Common
minecraft_version=1.20.1
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server
minecraft_version_range=[1.20.1,1.20.2]
description=


# Forge
forge_version=47.3.6
//forge_ats_enabled=true
forge_loader_version_range=[47,)
forge_version_range=[47,)

# Fabric
fabric_version=0.92.2+1.20.1
fabric_loader_version=0.16.2

# Mod options
mod_name=SmallerUnits
mod_author=GiantLuigi4, Mysticpasta1
mod_id=smallerunits

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# https://github.com/Creators-of-Create/Create/blob/mc1.20.1/dev/gradle.properties#L25-L26
flywheel_minecraft_version = 1.20.1
flywheel_version = 0.6.10-11
